name: Build

concurrency:
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '*.html'
      - '*.js'
      - '*.css'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          path: "src"

      - name: Checkout builds
        uses: actions/checkout@v3
        with:
          ref: "builds"
          path: "builds"

      - name: Clean old builds
        run: rm -f $GITHUB_WORKSPACE/builds/*.cs3 || true

      - name: Setup JDK 17 (required for latest Android SDK tools)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Android SDK (AGP 7.0.4 compatible)
        uses: android-actions/setup-android@v3

       - name: Remove invalid SDK directories (like android-33x, android-34x)
        run: |
          echo "Removing invalid SDK platform folders..."
          find $ANDROID_SDK_ROOT/platforms -maxdepth 1 -type d -name 'android-*' | grep -E 'android-[0-9]+[^0-9]' | xargs -r rm -rf

      - name: Install SDK platform and build tools
        run: sdkmanager "platforms;android-33" "build-tools;33.0.2"

      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew --no-daemon make makePluginsJson
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds
          cp build/plugins.json $GITHUB_WORKSPACE/builds

      - name: Push builds
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit --amend -m "Build $GITHUB_SHA" || exit 0
          git push --force-with-lease
